Repository hzi-braunschweig/SORMAS-Project, pull requests merged in 2020-10, with the labels that each got.

#2754 Introduce maven wrapper for local maven version
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: Community

#3057 [IMIS] fix for issue #2812
  sormas-ui/src/main/webapp/VAADIN/themes/sormas/components/grid.scss
Labels: small bugfix

#3319 #3317 Quarantine order download does not reliably start
  sormas-ui/src/main/java/de/symeda/sormas/ui/docgeneration/QuarantineOrderLayout.java
Labels: bug

#3323 [IMIS] #3322 spacing sideboxes
  sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataView.java
Labels: small bugfix

#3252 [IMIS] #3239 Dont copy phonenumber to email field when converting contact to case
  sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
Labels: small bugfix
